import Header from "@/components/Header/Header";
import Footer from "@/components/Footer";
import { Metadata } from "next";
import "./globals.css"


export const metadata: Metadata = {
  title: {
    default: "Mintech",
    template: "%s | Amin"
  },
  description: 'Generated by Mintech',
}

export default function RootLayout(
  {children}: {
    children: React.ReactNode
  }
) {
  return (
    <html lang="en">
      <body className="bg-background text-black">
        <div className="sticky top-0 inset-0">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}