import Header from "@/components/Header/Header";
import Footer from "@/components/Footer";
import { Metadata } from "next";
import "./globals.css"
import { AuthProvider } from "@/components/auth/AuthContext"
import { ToastContainer } from 'react-toastify';



export const metadata: Metadata = {
  title: {
    default: "Mintech",
    template: "%s | Amin"
  },
  description: 'Generated by Mintech',
}

export default function RootLayout(
  {children}: {
    children: React.ReactNode
  }
) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="bg-background text-black">
          <div className="sticky top-0 inset-0 z-10">
            <Header />
          </div>
          {children}
          <Footer />
          <ToastContainer />
        </body>
      </html>
    </AuthProvider>
  )
}